#!/usr/bin/env python3
"""
fix_mojibake.py - Corrige double-encoding UTF-8 (mojibake) em arquivos .md.

Problema: texto UTF-8 foi lido como Latin-1 e re-codificado como UTF-8,
gerando sequencias como "habilitacao" -> "habilitaÃ§Ã£o" em vez de "habilitação".

Estrategia:
  1. Tenta decodificar cada linha como latin1->utf8 (reversao exata do double-encoding)
  2. Se falhar para a linha inteira, tenta por segmentos (split em palavras)
  3. Fallback final: mapa de substituicoes conhecidas
"""

import os
import sys
import re
from pathlib import Path

# Known mojibake patterns: generated by encoding each accented char as UTF-8
# then decoding those bytes as Latin-1. We build this map programmatically.
MOJIBAKE_MAP = {}

# Build map from common Portuguese/Spanish accented characters
_CHARS = (
    "\u00e7\u00e3\u00e1\u00e9\u00f3\u00fa\u00ed\u00f4\u00ea\u00e2"  # ç ã á é ó ú í ô ê â
    "\u00e0\u00f1\u00fc\u00c9\u00d3\u00d5\u00c3\u00ef"               # à ñ ü É Ó Õ Ã ï
    "\u00c1\u00c2\u00c8\u00ca\u00cb\u00cc\u00cd\u00ce\u00cf"         # Á Â È Ê Ë Ì Í Î Ï
    "\u00d1\u00d2\u00d4\u00d6\u00d9\u00da\u00db\u00dc"               # Ñ Ò Ô Ö Ù Ú Û Ü
    "\u00e4\u00e5\u00e6\u00e8\u00eb\u00ec\u00ee\u00f0"               # ä å æ è ë ì î ð
    "\u00f2\u00f5\u00f6\u00f9\u00fb\u00fd\u00ff"                     # ò õ ö ù û ý ÿ
)

for ch in _CHARS:
    # What the double-encoding produces: encode char as UTF-8, interpret as Latin-1
    mojibake = ch.encode("utf-8").decode("latin-1")
    MOJIBAKE_MAP[mojibake] = ch


def fix_mojibake_line(line: str) -> str:
    """Try latin1-encode then utf8-decode (exact reversal). Fallback to map."""
    # Quick check: if no high bytes / mojibake marker, skip
    if "\u00c3" not in line:  # Ã is the marker for double-encoded UTF-8
        return line

    # Strategy 1: try full line reversal
    try:
        fixed = line.encode("latin-1").decode("utf-8")
        return fixed
    except (UnicodeDecodeError, UnicodeEncodeError):
        pass

    # Strategy 2: fallback replacement map (handles mixed content)
    result = line
    # Sort by length descending so longer sequences match first
    for bad, good in sorted(MOJIBAKE_MAP.items(), key=lambda x: -len(x[0])):
        result = result.replace(bad, good)
    return result


def fix_file(filepath: Path) -> tuple:
    """Fix a single file. Returns (was_changed, replacement_count)."""
    text = filepath.read_text(encoding="utf-8")
    lines = text.split("\n")
    new_lines = []
    total_replacements = 0

    for line in lines:
        fixed = fix_mojibake_line(line)
        if fixed != line:
            total_replacements += 1
        new_lines.append(fixed)

    if total_replacements == 0:
        return False, 0

    new_text = "\n".join(new_lines)
    filepath.write_text(new_text, encoding="utf-8")
    return True, total_replacements


def main():
    base_dir = Path(__file__).resolve().parent.parent / "src" / "kb" / "oracle-fusion-data-dictionary" / "docs"

    if len(sys.argv) > 1:
        scan_dir = Path(sys.argv[1])
    else:
        scan_dir = base_dir / "HCM" / "tables"

    if not scan_dir.exists():
        print(f"ERRO: diretorio nao encontrado: {scan_dir}")
        sys.exit(1)

    md_files = sorted(scan_dir.rglob("*.md"))
    print(f"Escaneando {len(md_files)} arquivos .md em {scan_dir}\n")

    fixed_count = 0
    total_lines_fixed = 0

    for f in md_files:
        changed, n = fix_file(f)
        if changed:
            fixed_count += 1
            total_lines_fixed += n
            print(f"  CORRIGIDO: {f.name} ({n} linhas)")

    print(f"\n{'='*60}")
    print(f"Arquivos escaneados: {len(md_files)}")
    print(f"Arquivos corrigidos: {fixed_count}")
    print(f"Linhas corrigidas:   {total_lines_fixed}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
